version: "3.8"
services:
  webapp:
    build: .
    env_file:
      - ".env"
    command: sh -c "/app/entrypoint.sh"
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ".env"
    volumes:
      - "postgres:/var/lib/postgresql/data"
volumes:
  postgres: {}